---
  - name: "{{ play_name }}"
    hosts: "{{ servers }}"
    vars:
      facts: no
    vars_files:
      - "install_packages_task-vars.yml"
      - "install_packages_play-vars.yml"
    gather_facts: "{{ facts }}"
    tasks:
      - name: Install packages on CentOS
        when: ansible_facts['distribution'] == "CentOS"
        yum:
          name: "{{ centos_packages }}"
          state: latest
      
      #- name: Install packages on Ubuntu
      #  when: ansible_facts['distribution'] == "Ubuntu"
      #  apt:
      #    name: "{{ packages }}"
      #    state: latest